#!/bin/bash
echo " porting [•] "
cp -r $HOME/.config/nvim $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/nvim && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [••]"
cp -r $HOME/.config/alacritty $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/alacritty && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [•••]"
cp -r $HOME/.config/dwm $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/dwm && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [••••]"
# cp -r $HOME/.config/picom $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/picom && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [•••••]"
cp -r $HOME/.config/rofi $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/rofi && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [••••••]"
cp -r $HOME/.config/zsh $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/zsh && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [•••••••]"
cp -r $HOME/.config/btop $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/btop && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [••••••••]"
cp -r $HOME/.config/starship $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/starship && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [•••••••••]"
cp -r $HOME/.config/lazygit $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/lazygit && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [••••••••••]"
# cp -r $HOME/.config/zellij $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/zellij && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [•••••••••••]"
# cp -r $HOME/.config/flamingo $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/flamingo && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [••••••••••••]"
# cp -r $HOME/.config/joshuto $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/joshuto && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [•••••••••••••]"
cp -r $HOME/.config/lf $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/lf && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [••••••••••••••]"
cp -r $HOME/.config/bat $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/bat && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [•••••••••••••••]"
# cp -r $HOME/.config/broot $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/broot && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [••••••••••••••••]"
cp -r $HOME/.config/waybar $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/waybar && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [•••••••••••••••••]"
cp -r $HOME/.config/hypr $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/hypr && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [••••••••••••••••••]"
# cp -r $HOME/.config/kitty $HOME/.config/dotfiles
echo -e "\e[1A\e[K porting [•••••••••••••••••••]"
cp -r $HOME/.config/swaylock $HOME/.config/dotfiles
echo -e "\e[1A\e[K porting [••••••••••••••••••••]"
cp -r $HOME/.config/wlogout $HOME/.config/dotfiles
echo -e "\e[1A\e[K porting [•••••••••••••••••••••]"
# cp -r /etc/lemurs $HOME/.config/dotfiles

cp -r $HOME/.z $HOME/.config/dotfiles
echo -e "\e[1A\e[K porting [••••••••••••••••••••••]"
cp -r $HOME/.zshrc $HOME/.config/dotfiles
echo -e "\e[1A\e[K porting [•••••••••••••••••••••••]"
cp -r $HOME/.zprofile $HOME/.config/dotfiles
echo -e "\e[1A\e[K porting [••••••••••••••••••••••••]"
cp -r $HOME/.xinitrc $HOME/.config/dotfiles
echo -e "\e[1A\e[K porting [•••••••••••••••••••••••••]"
cp -r $HOME/.histfile $HOME/.config/dotfiles
echo -e "\e[1A\e[K porting [••••••••••••••••••••••••••]"
cp -r $HOME/.zsh_history $HOME/.config/dotfiles
echo -e "\e[1A\e[K porting [•••••••••••••••••••••••••••]"
cp -r $HOME/.zshrc $HOME/.config/zsh/.zshrc
echo -e "\e[1A\e[K porting [••••••••••••••••••••••••••••]"
# cp -r $HOME/.vim $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/.vim && rm -rf .git* plugged autoload sessions && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [•••••••••••••••••••••••••••••]"
# cp -r $HOME/.mozilla/firefox/4yw0z4lr.default-release/chrome $HOME/.config/dotfiles
echo -e "\e[1A\e[K porting [••••••••••••••••••••••••••••••]"
# cp -r $HOME/.config/wezterm $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/wezterm && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [•••••••••••••••••••••••••••••••]"
# sudo cp -r /etc/lemurs > /dev/null 2>&1
# sudo cp -r /etc/pam.d/sudo . > /dev/null 2>&1
# sudo cp -r /etc/pam.d/login . > /dev/null 2>&1
# sudo cp -r /etc/pam.d/system-local-login . > /dev/null 2>&1
echo -e "\e[1A\e[K porting [••••••••••••••••••••••••••••••••]"
cp -r $HOME/.config/kanata $HOME/.config/dotfiles && cd $HOME/.config/dotfiles/kanata && rm -rf .git* && cd - > /dev/null 2>&1
echo -e "\e[1A\e[K porting [•••••••••••••••••••••••••••••••••]"
# sudo cp -r /etc/tlp.conf . > /dev/null 2>&1
# sudo cp -r /etc/systemd/system/powertop.service . > /dev/null 2>&1
echo -e "\e[1A\e[K porting [complete]"
