---
filtering: true
status-bar: true
title: Flamingo
editor: $EDITOR
pre-run: "rm -rf ~/.cache/nvim/server.pipe 2>/dev/null && clear &&"
flags: "--listen ~/.cache/nvim/server.pipe"
quit-key: "h"
select-key: "l"
projects:
  - title:   nvim
    description: ~/.config/nvim
  - title:   zellij
    description: ~/.config/zellij
  - title:   alacritty
    description: ~/.config/alacritty
  - title:   dwm
    description: ~/.config/dwm
  - title: 󱂛  manta-api
    description: ~/rust/canvas/manta-api
  - title:   zsh
    description: ~/.config/zsh
  - title:   lf
    description: ~/.config/lf
  - title:   flamingo (config)
    description: ~/.config/flamingo
  - title:   flamingo (dev)
    description: ~/go/src/github.com/Pheon-Dev/flamingo
  - title:   lazygit
    description: ~/.config/lazygit
  - title:   btop
    description: ~/.config/btop
  - title:   dotfiles
    description: ~/.config/dotfiles
  - title:   starship
    description: ~/.config/starship
  - title: 練  bat
    description: ~/.config/bat
  - title:   antelope (git)
    description: ~/Documents/neovim/antelope
  - title:    antelope (dev)
    description: ~/.local/share/nvim/lazy/antelope
  - title:   pigeon (git)
    description: ~/Documents/neovim/pigeon
  - title:   pigeon (dev)
    description: ~/.local/share/nvim/lazy/pigeon
  - title:   rofi
    description: ~/.config/rofi
  - title:   picom
    description: ~/.config/picom
  - title:   .xinitrc
    description: ~/.xinitrc
  - title:   .zshrc
    description: ~/.zshrc
