---
filtering: true
projects:
  - title:   nvim
    description: ~/.config/nvim
  - title:   zellij
    description: ~/.config/zellij
  - title:   alacritty
    description: ~/.config/alacritty
  - title:   dwm
    description: ~/.config/dwm
  - title:   manta-api
    description: ~/rust/canvas/manta-api
  - title:   zsh
    description: ~/.config/zsh
  - title:   lf
    description: ~/.config/lf
  # - title:   joshuto
  #   description: ~/.config/joshuto
  - title:   flamingo (config)
    description: ~/.config/flamingo
  - title:   flamingo (dev)
    description: ~/go/src/github.com/Pheon-Dev/flamingo
  - title:   lazygit
    description: ~/.config/lazygit
  - title:   btop
    description: ~/.config/btop
  - title:   dotfiles
    description: ~/dotfiles
  - title:   starship
    description: ~/.config/starship
  - title:   bat
    description: ~/.config/bat
  - title:   rofi
    description: ~/.config/rofi
  - title:   picom
    description: ~/.config/picom
  - title:   .xinitrc
    description: ~/.xinitrc
  - title:   .zshrc
    description: ~/.zshrc
status-bar: true
title: Flamingo
